name: Auto Label and Date ToDo Issue
on:
  issues:
    types: [opened]

jobs:
  update-title:
    if: startsWith(github.event.issue.title, 'ToDo-')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set Current Date
        run: echo "CURRENT_DATE=$(date -u +'%Y/%m/%d')" >> $GITHUB_ENV

      - name: Update Issue Title
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              title: `ToDo-${process.env.CURRENT_DATE}`
            })