name: Build LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          # for Chinese needed
          # latexmk_use_xelatex: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-summary-pdf
          path: main.pdf