name: Build LaTeX PDF

on:
  push:
    branches: [no_exist]
  #   branches: [ "conf_hri_25_clea" ]
  # pull_request:
  #   branches: [ "conf_hri_25_clea" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          # root_file: conf/HRI/25/CLEA/main.tex
          working_directory: conf/HRI/25/CLEA/

      # - name: Upload PDF artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: paper-summary-pdf
      #     path: main.pdf
      
      - name: Rename PDF
        run: |
          old_path="conf/HRI/25/CLEA/main.pdf"
          new_name="CLEA_summarization.pdf"
          mv "$old_path" "$new_name"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: CLEA_summarization_pdf
          path: CLEA_summarization.pdf


#  Orig Ver
# name: Build LaTeX PDF

# on:
#   push:
#     # branches: [ "main" ]
#     branches: [ "no_exist" ]
#   # pull_request:
#     # branches: [ "main" ]

# jobs:
#   build_latex:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Compile LaTeX document
#         uses: xu-cheng/latex-action@v3
#         with:
#           root_file: main.tex

#       # - name: Upload PDF artifact
#       #   uses: actions/upload-artifact@v4
#       #   with:
#       #     name: paper-summarization-template-pdf
#       #     path: main.pdf
      
#       - name: Rename PDF
#         run: |
#           old_path="main.pdf"
#           new_name="paper_summarization_template.pdf"
#           mv "$old_path" "$new_name"

#       - name: Upload PDF artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: paper-summarization-template-pdf
#           path: paper_summarization_template.pdf