name: Build LaTeX PDF

on:
  push:
    branches: [no_exist]
  #   branches: [ "journal_tro_24_learning_a_generalizable_trajectory_sampling_distrib_4_mpc" ]
  # pull_request:
  #   branches: [ "journal_tro_24_learning_a_generalizable_trajectory_sampling_distrib_4_mpc" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          # root_file: journal/TRO/24/learning_a_generalizable_trajectory_sampling_distrib_4_mpc/main.tex
          working_directory: journal/TRO/24/learning_a_generalizable_trajectory_sampling_distrib_4_mpc/

      # - name: Upload PDF artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: paper-summary-pdf
      #     path: main.pdf
      
      - name: Rename PDF
        run: |
          old_path="journal/TRO/24/learning_a_generalizable_trajectory_sampling_distrib_4_mpc/main.pdf"
          new_name="learning_a_generalizable_trajectory_sampling_distrib_4_mpc_summarization.pdf"
          mv "$old_path" "$new_name"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: learning_a_generalizable_trajectory_sampling_distrib_4_mpc_summarization_pdf
          path: learning_a_generalizable_trajectory_sampling_distrib_4_mpc_summarization.pdf